name: Docker container build

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Ensure tag is on master
        run: |
          git fetch origin master
          git branch --remote --contains $GITHUB_SHA | grep origin/master

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install cosign
        uses: sigstore/cosign-installer@v4.1.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4.2.0

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v4.2.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v4.6.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6.2.0
        with:
          images: |
            pouriyajamshidi/tcping
            ghcr.io/${{ github.repository }}

          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

          labels: |
            org.opencontainers.image.title=tcping
            org.opencontainers.image.description=Ping TCP ports. Inspired by Linux's ping utility. Written in Go
            org.opencontainers.image.vendor=Pouriya Jamshidi
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
